/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardCreateImport } from './routes/dashboard/create'
import { Route as DashboardDashboardLayoutImport } from './routes/dashboard/_dashboardLayout'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as DashboardDashboardLayoutVisualizationApiImport } from './routes/dashboard/_dashboardLayout/visualization-api'
import { Route as DashboardDashboardLayoutVisualizationImport } from './routes/dashboard/_dashboardLayout/visualization'
import { Route as DashboardDashboardLayoutRecipientImport } from './routes/dashboard/_dashboardLayout/recipient'
import { Route as DashboardDashboardLayoutProfileImport } from './routes/dashboard/_dashboardLayout/profile'
import { Route as DashboardDashboardLayoutHospitalHistoryImport } from './routes/dashboard/_dashboardLayout/hospital-history'
import { Route as DashboardDashboardLayoutEventsImport } from './routes/dashboard/_dashboardLayout/events'
import { Route as DashboardDashboardLayoutEditProfileImport } from './routes/dashboard/_dashboardLayout/edit-profile'
import { Route as DashboardDashboardLayoutEditPasswordImport } from './routes/dashboard/_dashboardLayout/edit-password'
import { Route as DashboardDashboardLayoutDonateImport } from './routes/dashboard/_dashboardLayout/donate'
import { Route as DashboardDashboardLayoutVisualizationLazyFixedImport } from './routes/dashboard/_dashboardLayout/visualization.lazy.fixed'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()
const DashboardDashboardLayoutIndexLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/',
)()
const DashboardDashboardLayoutCreateLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/create',
)()
const DashboardDashboardLayoutBloodtestsLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/bloodtests',
)()
const DashboardDashboardLayoutAnalyticsLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/analytics',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/index.lazy').then((d) => d.Route),
)

const DashboardCreateRoute = DashboardCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/create.lazy').then((d) => d.Route),
)

const DashboardDashboardLayoutRoute = DashboardDashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => DashboardRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardLayoutIndexLazyRoute =
  DashboardDashboardLayoutIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutCreateLazyRoute =
  DashboardDashboardLayoutCreateLazyImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/create.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutBloodtestsLazyRoute =
  DashboardDashboardLayoutBloodtestsLazyImport.update({
    id: '/bloodtests',
    path: '/bloodtests',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/bloodtests.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutAnalyticsLazyRoute =
  DashboardDashboardLayoutAnalyticsLazyImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/analytics.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutVisualizationApiRoute =
  DashboardDashboardLayoutVisualizationApiImport.update({
    id: '/visualization-api',
    path: '/visualization-api',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)

const DashboardDashboardLayoutVisualizationRoute =
  DashboardDashboardLayoutVisualizationImport.update({
    id: '/visualization',
    path: '/visualization',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/visualization.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutRecipientRoute =
  DashboardDashboardLayoutRecipientImport.update({
    id: '/recipient',
    path: '/recipient',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/recipient.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutProfileRoute =
  DashboardDashboardLayoutProfileImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/profile.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutHospitalHistoryRoute =
  DashboardDashboardLayoutHospitalHistoryImport.update({
    id: '/hospital-history',
    path: '/hospital-history',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/hospital-history.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutEventsRoute =
  DashboardDashboardLayoutEventsImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/events.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutEditProfileRoute =
  DashboardDashboardLayoutEditProfileImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/edit-profile.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutEditPasswordRoute =
  DashboardDashboardLayoutEditPasswordImport.update({
    id: '/edit-password',
    path: '/edit-password',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/edit-password.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutDonateRoute =
  DashboardDashboardLayoutDonateImport.update({
    id: '/donate',
    path: '/donate',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/donate.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutVisualizationLazyFixedRoute =
  DashboardDashboardLayoutVisualizationLazyFixedImport.update({
    id: '/lazy/fixed',
    path: '/lazy/fixed',
    getParentRoute: () => DashboardDashboardLayoutVisualizationRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/create': {
      id: '/dashboard/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardCreateImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/_dashboardLayout/donate': {
      id: '/dashboard/_dashboardLayout/donate'
      path: '/donate'
      fullPath: '/dashboard/donate'
      preLoaderRoute: typeof DashboardDashboardLayoutDonateImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/edit-password': {
      id: '/dashboard/_dashboardLayout/edit-password'
      path: '/edit-password'
      fullPath: '/dashboard/edit-password'
      preLoaderRoute: typeof DashboardDashboardLayoutEditPasswordImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/edit-profile': {
      id: '/dashboard/_dashboardLayout/edit-profile'
      path: '/edit-profile'
      fullPath: '/dashboard/edit-profile'
      preLoaderRoute: typeof DashboardDashboardLayoutEditProfileImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/events': {
      id: '/dashboard/_dashboardLayout/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardDashboardLayoutEventsImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/hospital-history': {
      id: '/dashboard/_dashboardLayout/hospital-history'
      path: '/hospital-history'
      fullPath: '/dashboard/hospital-history'
      preLoaderRoute: typeof DashboardDashboardLayoutHospitalHistoryImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/profile': {
      id: '/dashboard/_dashboardLayout/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardLayoutProfileImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/recipient': {
      id: '/dashboard/_dashboardLayout/recipient'
      path: '/recipient'
      fullPath: '/dashboard/recipient'
      preLoaderRoute: typeof DashboardDashboardLayoutRecipientImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/visualization': {
      id: '/dashboard/_dashboardLayout/visualization'
      path: '/visualization'
      fullPath: '/dashboard/visualization'
      preLoaderRoute: typeof DashboardDashboardLayoutVisualizationImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/visualization-api': {
      id: '/dashboard/_dashboardLayout/visualization-api'
      path: '/visualization-api'
      fullPath: '/dashboard/visualization-api'
      preLoaderRoute: typeof DashboardDashboardLayoutVisualizationApiImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/analytics': {
      id: '/dashboard/_dashboardLayout/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardDashboardLayoutAnalyticsLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/bloodtests': {
      id: '/dashboard/_dashboardLayout/bloodtests'
      path: '/bloodtests'
      fullPath: '/dashboard/bloodtests'
      preLoaderRoute: typeof DashboardDashboardLayoutBloodtestsLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/create': {
      id: '/dashboard/_dashboardLayout/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardDashboardLayoutCreateLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/': {
      id: '/dashboard/_dashboardLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardLayoutIndexLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/visualization/lazy/fixed': {
      id: '/dashboard/_dashboardLayout/visualization/lazy/fixed'
      path: '/lazy/fixed'
      fullPath: '/dashboard/visualization/lazy/fixed'
      preLoaderRoute: typeof DashboardDashboardLayoutVisualizationLazyFixedImport
      parentRoute: typeof DashboardDashboardLayoutVisualizationImport
    }
  }
}

// Create and export the route tree

interface DashboardDashboardLayoutVisualizationRouteChildren {
  DashboardDashboardLayoutVisualizationLazyFixedRoute: typeof DashboardDashboardLayoutVisualizationLazyFixedRoute
}

const DashboardDashboardLayoutVisualizationRouteChildren: DashboardDashboardLayoutVisualizationRouteChildren =
  {
    DashboardDashboardLayoutVisualizationLazyFixedRoute:
      DashboardDashboardLayoutVisualizationLazyFixedRoute,
  }

const DashboardDashboardLayoutVisualizationRouteWithChildren =
  DashboardDashboardLayoutVisualizationRoute._addFileChildren(
    DashboardDashboardLayoutVisualizationRouteChildren,
  )

interface DashboardDashboardLayoutRouteChildren {
  DashboardDashboardLayoutDonateRoute: typeof DashboardDashboardLayoutDonateRoute
  DashboardDashboardLayoutEditPasswordRoute: typeof DashboardDashboardLayoutEditPasswordRoute
  DashboardDashboardLayoutEditProfileRoute: typeof DashboardDashboardLayoutEditProfileRoute
  DashboardDashboardLayoutEventsRoute: typeof DashboardDashboardLayoutEventsRoute
  DashboardDashboardLayoutHospitalHistoryRoute: typeof DashboardDashboardLayoutHospitalHistoryRoute
  DashboardDashboardLayoutProfileRoute: typeof DashboardDashboardLayoutProfileRoute
  DashboardDashboardLayoutRecipientRoute: typeof DashboardDashboardLayoutRecipientRoute
  DashboardDashboardLayoutVisualizationRoute: typeof DashboardDashboardLayoutVisualizationRouteWithChildren
  DashboardDashboardLayoutVisualizationApiRoute: typeof DashboardDashboardLayoutVisualizationApiRoute
  DashboardDashboardLayoutAnalyticsLazyRoute: typeof DashboardDashboardLayoutAnalyticsLazyRoute
  DashboardDashboardLayoutBloodtestsLazyRoute: typeof DashboardDashboardLayoutBloodtestsLazyRoute
  DashboardDashboardLayoutCreateLazyRoute: typeof DashboardDashboardLayoutCreateLazyRoute
  DashboardDashboardLayoutIndexLazyRoute: typeof DashboardDashboardLayoutIndexLazyRoute
}

const DashboardDashboardLayoutRouteChildren: DashboardDashboardLayoutRouteChildren =
  {
    DashboardDashboardLayoutDonateRoute: DashboardDashboardLayoutDonateRoute,
    DashboardDashboardLayoutEditPasswordRoute:
      DashboardDashboardLayoutEditPasswordRoute,
    DashboardDashboardLayoutEditProfileRoute:
      DashboardDashboardLayoutEditProfileRoute,
    DashboardDashboardLayoutEventsRoute: DashboardDashboardLayoutEventsRoute,
    DashboardDashboardLayoutHospitalHistoryRoute:
      DashboardDashboardLayoutHospitalHistoryRoute,
    DashboardDashboardLayoutProfileRoute: DashboardDashboardLayoutProfileRoute,
    DashboardDashboardLayoutRecipientRoute:
      DashboardDashboardLayoutRecipientRoute,
    DashboardDashboardLayoutVisualizationRoute:
      DashboardDashboardLayoutVisualizationRouteWithChildren,
    DashboardDashboardLayoutVisualizationApiRoute:
      DashboardDashboardLayoutVisualizationApiRoute,
    DashboardDashboardLayoutAnalyticsLazyRoute:
      DashboardDashboardLayoutAnalyticsLazyRoute,
    DashboardDashboardLayoutBloodtestsLazyRoute:
      DashboardDashboardLayoutBloodtestsLazyRoute,
    DashboardDashboardLayoutCreateLazyRoute:
      DashboardDashboardLayoutCreateLazyRoute,
    DashboardDashboardLayoutIndexLazyRoute:
      DashboardDashboardLayoutIndexLazyRoute,
  }

const DashboardDashboardLayoutRouteWithChildren =
  DashboardDashboardLayoutRoute._addFileChildren(
    DashboardDashboardLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRouteWithChildren
  DashboardCreateRoute: typeof DashboardCreateRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRouteWithChildren,
  DashboardCreateRoute: DashboardCreateRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof DashboardDashboardLayoutRouteWithChildren
  '/dashboard/create': typeof DashboardDashboardLayoutCreateLazyRoute
  '/dashboard/': typeof DashboardDashboardLayoutIndexLazyRoute
  '/dashboard/donate': typeof DashboardDashboardLayoutDonateRoute
  '/dashboard/edit-password': typeof DashboardDashboardLayoutEditPasswordRoute
  '/dashboard/edit-profile': typeof DashboardDashboardLayoutEditProfileRoute
  '/dashboard/events': typeof DashboardDashboardLayoutEventsRoute
  '/dashboard/hospital-history': typeof DashboardDashboardLayoutHospitalHistoryRoute
  '/dashboard/profile': typeof DashboardDashboardLayoutProfileRoute
  '/dashboard/recipient': typeof DashboardDashboardLayoutRecipientRoute
  '/dashboard/visualization': typeof DashboardDashboardLayoutVisualizationRouteWithChildren
  '/dashboard/visualization-api': typeof DashboardDashboardLayoutVisualizationApiRoute
  '/dashboard/analytics': typeof DashboardDashboardLayoutAnalyticsLazyRoute
  '/dashboard/bloodtests': typeof DashboardDashboardLayoutBloodtestsLazyRoute
  '/dashboard/visualization/lazy/fixed': typeof DashboardDashboardLayoutVisualizationLazyFixedRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard/create': typeof DashboardDashboardLayoutCreateLazyRoute
  '/dashboard': typeof DashboardDashboardLayoutIndexLazyRoute
  '/dashboard/donate': typeof DashboardDashboardLayoutDonateRoute
  '/dashboard/edit-password': typeof DashboardDashboardLayoutEditPasswordRoute
  '/dashboard/edit-profile': typeof DashboardDashboardLayoutEditProfileRoute
  '/dashboard/events': typeof DashboardDashboardLayoutEventsRoute
  '/dashboard/hospital-history': typeof DashboardDashboardLayoutHospitalHistoryRoute
  '/dashboard/profile': typeof DashboardDashboardLayoutProfileRoute
  '/dashboard/recipient': typeof DashboardDashboardLayoutRecipientRoute
  '/dashboard/visualization': typeof DashboardDashboardLayoutVisualizationRouteWithChildren
  '/dashboard/visualization-api': typeof DashboardDashboardLayoutVisualizationApiRoute
  '/dashboard/analytics': typeof DashboardDashboardLayoutAnalyticsLazyRoute
  '/dashboard/bloodtests': typeof DashboardDashboardLayoutBloodtestsLazyRoute
  '/dashboard/visualization/lazy/fixed': typeof DashboardDashboardLayoutVisualizationLazyFixedRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRouteWithChildren
  '/dashboard/create': typeof DashboardCreateRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/_dashboardLayout/donate': typeof DashboardDashboardLayoutDonateRoute
  '/dashboard/_dashboardLayout/edit-password': typeof DashboardDashboardLayoutEditPasswordRoute
  '/dashboard/_dashboardLayout/edit-profile': typeof DashboardDashboardLayoutEditProfileRoute
  '/dashboard/_dashboardLayout/events': typeof DashboardDashboardLayoutEventsRoute
  '/dashboard/_dashboardLayout/hospital-history': typeof DashboardDashboardLayoutHospitalHistoryRoute
  '/dashboard/_dashboardLayout/profile': typeof DashboardDashboardLayoutProfileRoute
  '/dashboard/_dashboardLayout/recipient': typeof DashboardDashboardLayoutRecipientRoute
  '/dashboard/_dashboardLayout/visualization': typeof DashboardDashboardLayoutVisualizationRouteWithChildren
  '/dashboard/_dashboardLayout/visualization-api': typeof DashboardDashboardLayoutVisualizationApiRoute
  '/dashboard/_dashboardLayout/analytics': typeof DashboardDashboardLayoutAnalyticsLazyRoute
  '/dashboard/_dashboardLayout/bloodtests': typeof DashboardDashboardLayoutBloodtestsLazyRoute
  '/dashboard/_dashboardLayout/create': typeof DashboardDashboardLayoutCreateLazyRoute
  '/dashboard/_dashboardLayout/': typeof DashboardDashboardLayoutIndexLazyRoute
  '/dashboard/_dashboardLayout/visualization/lazy/fixed': typeof DashboardDashboardLayoutVisualizationLazyFixedRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/dashboard'
    | '/dashboard/create'
    | '/dashboard/'
    | '/dashboard/donate'
    | '/dashboard/edit-password'
    | '/dashboard/edit-profile'
    | '/dashboard/events'
    | '/dashboard/hospital-history'
    | '/dashboard/profile'
    | '/dashboard/recipient'
    | '/dashboard/visualization'
    | '/dashboard/visualization-api'
    | '/dashboard/analytics'
    | '/dashboard/bloodtests'
    | '/dashboard/visualization/lazy/fixed'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/dashboard/create'
    | '/dashboard'
    | '/dashboard/donate'
    | '/dashboard/edit-password'
    | '/dashboard/edit-profile'
    | '/dashboard/events'
    | '/dashboard/hospital-history'
    | '/dashboard/profile'
    | '/dashboard/recipient'
    | '/dashboard/visualization'
    | '/dashboard/visualization-api'
    | '/dashboard/analytics'
    | '/dashboard/bloodtests'
    | '/dashboard/visualization/lazy/fixed'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/dashboard'
    | '/dashboard/_dashboardLayout'
    | '/dashboard/create'
    | '/dashboard/'
    | '/dashboard/_dashboardLayout/donate'
    | '/dashboard/_dashboardLayout/edit-password'
    | '/dashboard/_dashboardLayout/edit-profile'
    | '/dashboard/_dashboardLayout/events'
    | '/dashboard/_dashboardLayout/hospital-history'
    | '/dashboard/_dashboardLayout/profile'
    | '/dashboard/_dashboardLayout/recipient'
    | '/dashboard/_dashboardLayout/visualization'
    | '/dashboard/_dashboardLayout/visualization-api'
    | '/dashboard/_dashboardLayout/analytics'
    | '/dashboard/_dashboardLayout/bloodtests'
    | '/dashboard/_dashboardLayout/create'
    | '/dashboard/_dashboardLayout/'
    | '/dashboard/_dashboardLayout/visualization/lazy/fixed'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)/login",
        "/(auth)/sign-up",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashboardLayout",
        "/dashboard/create",
        "/dashboard/"
      ]
    },
    "/dashboard/_dashboardLayout": {
      "filePath": "dashboard/_dashboardLayout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashboardLayout/donate",
        "/dashboard/_dashboardLayout/edit-password",
        "/dashboard/_dashboardLayout/edit-profile",
        "/dashboard/_dashboardLayout/events",
        "/dashboard/_dashboardLayout/hospital-history",
        "/dashboard/_dashboardLayout/profile",
        "/dashboard/_dashboardLayout/recipient",
        "/dashboard/_dashboardLayout/visualization",
        "/dashboard/_dashboardLayout/visualization-api",
        "/dashboard/_dashboardLayout/analytics",
        "/dashboard/_dashboardLayout/bloodtests",
        "/dashboard/_dashboardLayout/create",
        "/dashboard/_dashboardLayout/"
      ]
    },
    "/dashboard/create": {
      "filePath": "dashboard/create.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/_dashboardLayout/donate": {
      "filePath": "dashboard/_dashboardLayout/donate.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/edit-password": {
      "filePath": "dashboard/_dashboardLayout/edit-password.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/edit-profile": {
      "filePath": "dashboard/_dashboardLayout/edit-profile.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/events": {
      "filePath": "dashboard/_dashboardLayout/events.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/hospital-history": {
      "filePath": "dashboard/_dashboardLayout/hospital-history.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/profile": {
      "filePath": "dashboard/_dashboardLayout/profile.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/recipient": {
      "filePath": "dashboard/_dashboardLayout/recipient.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/visualization": {
      "filePath": "dashboard/_dashboardLayout/visualization.tsx",
      "parent": "/dashboard/_dashboardLayout",
      "children": [
        "/dashboard/_dashboardLayout/visualization/lazy/fixed"
      ]
    },
    "/dashboard/_dashboardLayout/visualization-api": {
      "filePath": "dashboard/_dashboardLayout/visualization-api.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/analytics": {
      "filePath": "dashboard/_dashboardLayout/analytics.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/bloodtests": {
      "filePath": "dashboard/_dashboardLayout/bloodtests.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/create": {
      "filePath": "dashboard/_dashboardLayout/create.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/": {
      "filePath": "dashboard/_dashboardLayout/index.lazy.jsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/visualization/lazy/fixed": {
      "filePath": "dashboard/_dashboardLayout/visualization.lazy.fixed.tsx",
      "parent": "/dashboard/_dashboardLayout/visualization"
    }
  }
}
ROUTE_MANIFEST_END */
