/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardDashboardLayoutImport } from './routes/dashboard/_dashboardLayout'
import { Route as authSignUpImport } from './routes/(auth)/sign-up'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as DashboardDashboardLayoutVisualizationApiImport } from './routes/dashboard/_dashboardLayout/visualization-api'

// Create Virtual Routes

const DashboardImport = createFileRoute('/dashboard')()
const DashboardDashboardLayoutIndexLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/',
)()
const DashboardDashboardLayoutVisualizationLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/visualization',
)()
const DashboardDashboardLayoutRecipientLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/recipient',
)()
const DashboardDashboardLayoutProfileLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/profile',
)()
const DashboardDashboardLayoutHospitalHistoryLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/hospital-history',
)()
const DashboardDashboardLayoutEventsLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/events',
)()
const DashboardDashboardLayoutEditProfileLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/edit-profile',
)()
const DashboardDashboardLayoutDonateLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/donate',
)()
const DashboardDashboardLayoutCreateLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/create',
)()
const DashboardDashboardLayoutBloodtestsLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/bloodtests',
)()
const DashboardDashboardLayoutAnalyticsLazyImport = createFileRoute(
  '/dashboard/_dashboardLayout/analytics',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardLayoutRoute = DashboardDashboardLayoutImport.update({
  id: '/_dashboardLayout',
  getParentRoute: () => DashboardRoute,
} as any)

const authSignUpRoute = authSignUpImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const DashboardDashboardLayoutIndexLazyRoute =
  DashboardDashboardLayoutIndexLazyImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/index.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutVisualizationLazyRoute =
  DashboardDashboardLayoutVisualizationLazyImport.update({
    id: '/visualization',
    path: '/visualization',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/visualization.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutRecipientLazyRoute =
  DashboardDashboardLayoutRecipientLazyImport.update({
    id: '/recipient',
    path: '/recipient',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/recipient.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutProfileLazyRoute =
  DashboardDashboardLayoutProfileLazyImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/profile.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutHospitalHistoryLazyRoute =
  DashboardDashboardLayoutHospitalHistoryLazyImport.update({
    id: '/hospital-history',
    path: '/hospital-history',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/hospital-history.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutEventsLazyRoute =
  DashboardDashboardLayoutEventsLazyImport.update({
    id: '/events',
    path: '/events',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/events.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutEditProfileLazyRoute =
  DashboardDashboardLayoutEditProfileLazyImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/edit-profile.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutDonateLazyRoute =
  DashboardDashboardLayoutDonateLazyImport.update({
    id: '/donate',
    path: '/donate',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/donate.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutCreateLazyRoute =
  DashboardDashboardLayoutCreateLazyImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/create.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutBloodtestsLazyRoute =
  DashboardDashboardLayoutBloodtestsLazyImport.update({
    id: '/bloodtests',
    path: '/bloodtests',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/bloodtests.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutAnalyticsLazyRoute =
  DashboardDashboardLayoutAnalyticsLazyImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/_dashboardLayout/analytics.lazy').then(
      (d) => d.Route,
    ),
  )

const DashboardDashboardLayoutVisualizationApiRoute =
  DashboardDashboardLayoutVisualizationApiImport.update({
    id: '/visualization-api',
    path: '/visualization-api',
    getParentRoute: () => DashboardDashboardLayoutRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/_dashboardLayout': {
      id: '/dashboard/_dashboardLayout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardDashboardLayoutImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/_dashboardLayout/visualization-api': {
      id: '/dashboard/_dashboardLayout/visualization-api'
      path: '/visualization-api'
      fullPath: '/dashboard/visualization-api'
      preLoaderRoute: typeof DashboardDashboardLayoutVisualizationApiImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/analytics': {
      id: '/dashboard/_dashboardLayout/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardDashboardLayoutAnalyticsLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/bloodtests': {
      id: '/dashboard/_dashboardLayout/bloodtests'
      path: '/bloodtests'
      fullPath: '/dashboard/bloodtests'
      preLoaderRoute: typeof DashboardDashboardLayoutBloodtestsLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/create': {
      id: '/dashboard/_dashboardLayout/create'
      path: '/create'
      fullPath: '/dashboard/create'
      preLoaderRoute: typeof DashboardDashboardLayoutCreateLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/donate': {
      id: '/dashboard/_dashboardLayout/donate'
      path: '/donate'
      fullPath: '/dashboard/donate'
      preLoaderRoute: typeof DashboardDashboardLayoutDonateLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/edit-profile': {
      id: '/dashboard/_dashboardLayout/edit-profile'
      path: '/edit-profile'
      fullPath: '/dashboard/edit-profile'
      preLoaderRoute: typeof DashboardDashboardLayoutEditProfileLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/events': {
      id: '/dashboard/_dashboardLayout/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardDashboardLayoutEventsLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/hospital-history': {
      id: '/dashboard/_dashboardLayout/hospital-history'
      path: '/hospital-history'
      fullPath: '/dashboard/hospital-history'
      preLoaderRoute: typeof DashboardDashboardLayoutHospitalHistoryLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/profile': {
      id: '/dashboard/_dashboardLayout/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardLayoutProfileLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/recipient': {
      id: '/dashboard/_dashboardLayout/recipient'
      path: '/recipient'
      fullPath: '/dashboard/recipient'
      preLoaderRoute: typeof DashboardDashboardLayoutRecipientLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/visualization': {
      id: '/dashboard/_dashboardLayout/visualization'
      path: '/visualization'
      fullPath: '/dashboard/visualization'
      preLoaderRoute: typeof DashboardDashboardLayoutVisualizationLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
    '/dashboard/_dashboardLayout/': {
      id: '/dashboard/_dashboardLayout/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardLayoutIndexLazyImport
      parentRoute: typeof DashboardDashboardLayoutImport
    }
  }
}

// Create and export the route tree

interface DashboardDashboardLayoutRouteChildren {
  DashboardDashboardLayoutVisualizationApiRoute: typeof DashboardDashboardLayoutVisualizationApiRoute
  DashboardDashboardLayoutAnalyticsLazyRoute: typeof DashboardDashboardLayoutAnalyticsLazyRoute
  DashboardDashboardLayoutBloodtestsLazyRoute: typeof DashboardDashboardLayoutBloodtestsLazyRoute
  DashboardDashboardLayoutCreateLazyRoute: typeof DashboardDashboardLayoutCreateLazyRoute
  DashboardDashboardLayoutDonateLazyRoute: typeof DashboardDashboardLayoutDonateLazyRoute
  DashboardDashboardLayoutEditProfileLazyRoute: typeof DashboardDashboardLayoutEditProfileLazyRoute
  DashboardDashboardLayoutEventsLazyRoute: typeof DashboardDashboardLayoutEventsLazyRoute
  DashboardDashboardLayoutHospitalHistoryLazyRoute: typeof DashboardDashboardLayoutHospitalHistoryLazyRoute
  DashboardDashboardLayoutProfileLazyRoute: typeof DashboardDashboardLayoutProfileLazyRoute
  DashboardDashboardLayoutRecipientLazyRoute: typeof DashboardDashboardLayoutRecipientLazyRoute
  DashboardDashboardLayoutVisualizationLazyRoute: typeof DashboardDashboardLayoutVisualizationLazyRoute
  DashboardDashboardLayoutIndexLazyRoute: typeof DashboardDashboardLayoutIndexLazyRoute
}

const DashboardDashboardLayoutRouteChildren: DashboardDashboardLayoutRouteChildren =
  {
    DashboardDashboardLayoutVisualizationApiRoute:
      DashboardDashboardLayoutVisualizationApiRoute,
    DashboardDashboardLayoutAnalyticsLazyRoute:
      DashboardDashboardLayoutAnalyticsLazyRoute,
    DashboardDashboardLayoutBloodtestsLazyRoute:
      DashboardDashboardLayoutBloodtestsLazyRoute,
    DashboardDashboardLayoutCreateLazyRoute:
      DashboardDashboardLayoutCreateLazyRoute,
    DashboardDashboardLayoutDonateLazyRoute:
      DashboardDashboardLayoutDonateLazyRoute,
    DashboardDashboardLayoutEditProfileLazyRoute:
      DashboardDashboardLayoutEditProfileLazyRoute,
    DashboardDashboardLayoutEventsLazyRoute:
      DashboardDashboardLayoutEventsLazyRoute,
    DashboardDashboardLayoutHospitalHistoryLazyRoute:
      DashboardDashboardLayoutHospitalHistoryLazyRoute,
    DashboardDashboardLayoutProfileLazyRoute:
      DashboardDashboardLayoutProfileLazyRoute,
    DashboardDashboardLayoutRecipientLazyRoute:
      DashboardDashboardLayoutRecipientLazyRoute,
    DashboardDashboardLayoutVisualizationLazyRoute:
      DashboardDashboardLayoutVisualizationLazyRoute,
    DashboardDashboardLayoutIndexLazyRoute:
      DashboardDashboardLayoutIndexLazyRoute,
  }

const DashboardDashboardLayoutRouteWithChildren =
  DashboardDashboardLayoutRoute._addFileChildren(
    DashboardDashboardLayoutRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardLayoutRoute: typeof DashboardDashboardLayoutRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardLayoutRoute: DashboardDashboardLayoutRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof DashboardDashboardLayoutRouteWithChildren
  '/dashboard/visualization-api': typeof DashboardDashboardLayoutVisualizationApiRoute
  '/dashboard/analytics': typeof DashboardDashboardLayoutAnalyticsLazyRoute
  '/dashboard/bloodtests': typeof DashboardDashboardLayoutBloodtestsLazyRoute
  '/dashboard/create': typeof DashboardDashboardLayoutCreateLazyRoute
  '/dashboard/donate': typeof DashboardDashboardLayoutDonateLazyRoute
  '/dashboard/edit-profile': typeof DashboardDashboardLayoutEditProfileLazyRoute
  '/dashboard/events': typeof DashboardDashboardLayoutEventsLazyRoute
  '/dashboard/hospital-history': typeof DashboardDashboardLayoutHospitalHistoryLazyRoute
  '/dashboard/profile': typeof DashboardDashboardLayoutProfileLazyRoute
  '/dashboard/recipient': typeof DashboardDashboardLayoutRecipientLazyRoute
  '/dashboard/visualization': typeof DashboardDashboardLayoutVisualizationLazyRoute
  '/dashboard/': typeof DashboardDashboardLayoutIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof DashboardDashboardLayoutIndexLazyRoute
  '/dashboard/visualization-api': typeof DashboardDashboardLayoutVisualizationApiRoute
  '/dashboard/analytics': typeof DashboardDashboardLayoutAnalyticsLazyRoute
  '/dashboard/bloodtests': typeof DashboardDashboardLayoutBloodtestsLazyRoute
  '/dashboard/create': typeof DashboardDashboardLayoutCreateLazyRoute
  '/dashboard/donate': typeof DashboardDashboardLayoutDonateLazyRoute
  '/dashboard/edit-profile': typeof DashboardDashboardLayoutEditProfileLazyRoute
  '/dashboard/events': typeof DashboardDashboardLayoutEventsLazyRoute
  '/dashboard/hospital-history': typeof DashboardDashboardLayoutHospitalHistoryLazyRoute
  '/dashboard/profile': typeof DashboardDashboardLayoutProfileLazyRoute
  '/dashboard/recipient': typeof DashboardDashboardLayoutRecipientLazyRoute
  '/dashboard/visualization': typeof DashboardDashboardLayoutVisualizationLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/_dashboardLayout': typeof DashboardDashboardLayoutRouteWithChildren
  '/dashboard/_dashboardLayout/visualization-api': typeof DashboardDashboardLayoutVisualizationApiRoute
  '/dashboard/_dashboardLayout/analytics': typeof DashboardDashboardLayoutAnalyticsLazyRoute
  '/dashboard/_dashboardLayout/bloodtests': typeof DashboardDashboardLayoutBloodtestsLazyRoute
  '/dashboard/_dashboardLayout/create': typeof DashboardDashboardLayoutCreateLazyRoute
  '/dashboard/_dashboardLayout/donate': typeof DashboardDashboardLayoutDonateLazyRoute
  '/dashboard/_dashboardLayout/edit-profile': typeof DashboardDashboardLayoutEditProfileLazyRoute
  '/dashboard/_dashboardLayout/events': typeof DashboardDashboardLayoutEventsLazyRoute
  '/dashboard/_dashboardLayout/hospital-history': typeof DashboardDashboardLayoutHospitalHistoryLazyRoute
  '/dashboard/_dashboardLayout/profile': typeof DashboardDashboardLayoutProfileLazyRoute
  '/dashboard/_dashboardLayout/recipient': typeof DashboardDashboardLayoutRecipientLazyRoute
  '/dashboard/_dashboardLayout/visualization': typeof DashboardDashboardLayoutVisualizationLazyRoute
  '/dashboard/_dashboardLayout/': typeof DashboardDashboardLayoutIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sign-up'
    | '/dashboard'
    | '/dashboard/visualization-api'
    | '/dashboard/analytics'
    | '/dashboard/bloodtests'
    | '/dashboard/create'
    | '/dashboard/donate'
    | '/dashboard/edit-profile'
    | '/dashboard/events'
    | '/dashboard/hospital-history'
    | '/dashboard/profile'
    | '/dashboard/recipient'
    | '/dashboard/visualization'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/sign-up'
    | '/dashboard'
    | '/dashboard/visualization-api'
    | '/dashboard/analytics'
    | '/dashboard/bloodtests'
    | '/dashboard/create'
    | '/dashboard/donate'
    | '/dashboard/edit-profile'
    | '/dashboard/events'
    | '/dashboard/hospital-history'
    | '/dashboard/profile'
    | '/dashboard/recipient'
    | '/dashboard/visualization'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/sign-up'
    | '/dashboard'
    | '/dashboard/_dashboardLayout'
    | '/dashboard/_dashboardLayout/visualization-api'
    | '/dashboard/_dashboardLayout/analytics'
    | '/dashboard/_dashboardLayout/bloodtests'
    | '/dashboard/_dashboardLayout/create'
    | '/dashboard/_dashboardLayout/donate'
    | '/dashboard/_dashboardLayout/edit-profile'
    | '/dashboard/_dashboardLayout/events'
    | '/dashboard/_dashboardLayout/hospital-history'
    | '/dashboard/_dashboardLayout/profile'
    | '/dashboard/_dashboardLayout/recipient'
    | '/dashboard/_dashboardLayout/visualization'
    | '/dashboard/_dashboardLayout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authSignUpRoute: typeof authSignUpRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authSignUpRoute: authSignUpRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/(auth)/login",
        "/(auth)/sign-up",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/(auth)/sign-up": {
      "filePath": "(auth)/sign-up.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard",
      "children": [
        "/dashboard/_dashboardLayout"
      ]
    },
    "/dashboard/_dashboardLayout": {
      "filePath": "dashboard/_dashboardLayout.tsx",
      "parent": "/dashboard",
      "children": [
        "/dashboard/_dashboardLayout/visualization-api",
        "/dashboard/_dashboardLayout/analytics",
        "/dashboard/_dashboardLayout/bloodtests",
        "/dashboard/_dashboardLayout/create",
        "/dashboard/_dashboardLayout/donate",
        "/dashboard/_dashboardLayout/edit-profile",
        "/dashboard/_dashboardLayout/events",
        "/dashboard/_dashboardLayout/hospital-history",
        "/dashboard/_dashboardLayout/profile",
        "/dashboard/_dashboardLayout/recipient",
        "/dashboard/_dashboardLayout/visualization",
        "/dashboard/_dashboardLayout/"
      ]
    },
    "/dashboard/_dashboardLayout/visualization-api": {
      "filePath": "dashboard/_dashboardLayout/visualization-api.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/analytics": {
      "filePath": "dashboard/_dashboardLayout/analytics.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/bloodtests": {
      "filePath": "dashboard/_dashboardLayout/bloodtests.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/create": {
      "filePath": "dashboard/_dashboardLayout/create.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/donate": {
      "filePath": "dashboard/_dashboardLayout/donate.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/edit-profile": {
      "filePath": "dashboard/_dashboardLayout/edit-profile.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/events": {
      "filePath": "dashboard/_dashboardLayout/events.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/hospital-history": {
      "filePath": "dashboard/_dashboardLayout/hospital-history.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/profile": {
      "filePath": "dashboard/_dashboardLayout/profile.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/recipient": {
      "filePath": "dashboard/_dashboardLayout/recipient.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/visualization": {
      "filePath": "dashboard/_dashboardLayout/visualization.lazy.tsx",
      "parent": "/dashboard/_dashboardLayout"
    },
    "/dashboard/_dashboardLayout/": {
      "filePath": "dashboard/_dashboardLayout/index.lazy.jsx",
      "parent": "/dashboard/_dashboardLayout"
    }
  }
}
ROUTE_MANIFEST_END */
